package org.remus.giteabot.prworkflow.e2e;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PrTestSuiteRepository extends JpaRepository<PrTestSuite, Long> {

    List<PrTestSuite> findByPrNumberAndLifecycleMode(Long prNumber, SuiteLifecycleMode lifecycleMode);

    /**
     * M7 promotion GC: every suite generated by a given {@link
     * org.remus.giteabot.prworkflow.PrWorkflowRun}. Used by
     * {@link org.remus.giteabot.prworkflow.e2e.promotion.PromotedSuiteGarbageCollector}
     * to delete the suite (and its cases via {@code orphanRemoval=true})
     * once the corresponding follow-up PR has been around long enough
     * that we no longer need the persisted source-of-truth.
     */
    List<PrTestSuite> findByRunId(Long runId);
}
